version: "3.8"  # optional since v1.27.0
services:
  hadoop-master:
    container_name: "hadoop-master"
    hostname: "hadoop-master"
    image: "totofunku/bigdata-cours:upgrade"
    ports:
      - "8080:8088"
      - "9870:9870"
      - "8040:8042"
      - "7077:7077"
      - "16010:16010"
    networks:
      - hadoop
    stdin_open: true
    tty: true

  hadoop-slave1:
    container_name: "hadoop-slave1"
    hostname: "hadoop-slave1"
    image: "totofunku/bigdata-cours:upgrade"
    ports: 
      - "8041:8042"
    depends_on:
      - hadoop-master 
    networks:
      - hadoop
    stdin_open: true
    tty: true

  hadoop-slave2:
    container_name: "hadoop-slave2"
    hostname: "hadoop-slave2"
    image: "totofunku/bigdata-cours:upgrade"
    ports:
      - "8042:8042"
    depends_on:
      - hadoop-master
    networks:
      - hadoop
    stdin_open: true
    tty: true

networks:
  hadoop:
