version: "3.8"  # optional since v1.27.0
services:
  hadoop-master:
    container_name: "hadoop-master"
    hostname: "hadoop-master"
    image: "liliasfaxi/spark-hadoop:hv-2.7.2"
    ports:
      - "8080:8088"
      - "9870:9870"
      - "8040:8042"
      - "7077:7077"
      - "16010:16010"
    networks:
      - hadoop
    depends_on:
      - hadoop-slave1
      - hadoop-slave2
    stdin_open: true
    tty: true

  hadoop-slave1:
    container_name: "hadoop-slave1"
    hostname: "hadoop-slave1"
    image: "liliasfaxi/spark-hadoop:hv-2.7.2"
    ports: 
      - "8041:8042"
    networks:
      - hadoop
    stdin_open: true
    tty: true

  hadoop-slave2:
    container_name: "hadoop-slave2"
    hostname: "hadoop-slave2"
    image: "liliasfaxi/spark-hadoop:hv-2.7.2"
    ports:
      - "8042:8042"
    networks:
      - hadoop
    stdin_open: true
    tty: true

networks:
  hadoop:
